export const sideBarLinks = [
  { name: "Home", icon: "icons/home.svg" },
  { name: "Messages", icon: "icons/message.svg" },
  { name: "Tasks", icon: "icons/task-square.svg" },
  { name: "Members", icon: "icons/profile-2users.svg" },
  { name: "Settings", icon: "icons/settings.svg" },
];

export const projects = [
  "Mobile App",
  "Website Redesign",
  "Design System",
  "Wireframes",
];

export const initData = {
  tasks: {
    1: {
      id: 1,
      urgency: "Low",
      status: "To Do",
      title: "Brainstorming",
      desc: "Brainstorming brings team members' diverse experience into play.",
      collaborators: [
        "/images/team-member-1.png",
        "/images/team-member-4.png",
        "/images/team-member-3.png",
      ],
      comments: 12,
      files: 0,
    },
    2: {
      id: 2,
      urgency: "High",
      status: "To Do",
      title: "Research",
      desc: "User research helps you to create an optimal product for users.",
      collaborators: ["/images/team-member-1.png", "/images/team-member-4.png"],
      comments: 10,
      files: 3,
    },
    3: {
      id: 3,
      urgency: "High",
      status: "To Do",
      title: "Wireframes",
      desc: "Low fidelity wireframes include the most basic content and visuals.",
      collaborators: [
        "/images/team-member-1.png",
        "/images/team-member-4.png",
        "/images/team-member-3.png",
      ],
      comments: 15,
      files: 5,
    },
    4: {
      id: 4,
      urgency: "High",
      status: "To Do",
      title: "Wireframes",
      desc: "Low fidelity wireframes include the most basic content and visuals.",
      collaborators: ["/images/team-member-1.png", "/images/team-member-3.png"],
      comments: 7,
      files: 2,
    },
    5: {
      id: 5,
      urgency: "Low",
      status: "On Progress",
      title: "Onboarding Illustrations",
      imgs: ["onboarding"],
      collaborators: ["/images/team-member-1.png", "/images/team-member-3.png"],
      comments: 14,
      files: 15,
    },
    6: {
      id: 6,
      urgency: "Low",
      status: "On Progress",
      title: "Moodboard",
      imgs: ["mood-board-1", "mood-board-2"],
      collaborators: ["/images/team-member-1.png", "/images/team-member-3.png"],
      comments: 9,
      files: 10,
    },
    7: {
      id: 7,
      urgency: "Low",
      status: "Done",
      title: "Mobile App Design",
      imgs: ["mobile-app-design"],
      collaborators: ["/images/team-member-1.png", "/images/team-member-3.png"],
      comments: 12,
      files: 15,
    },
    8: {
      id: 8,
      urgency: "High",
      status: "Done",
      title: "Design System",
      desc: "It just needs to adapt the UI from what you did before.",
      collaborators: ["/images/team-member-1.png", "/images/team-member-3.png"],
      comments: 12,
      files: 15,
    },
  },
  stages: {
    "stage-1": {
      id: "stage-1",
      title: "To Do",
      tasksIds: [1, 2, 3, 4],
    },
    "stage-2": {
      id: "stage-2",
      title: "On Progress",
      tasksIds: [5, 6],
    },
    "stage-3": {
      id: "stage-2",
      title: "Done",
      tasksIds: [7, 8],
    },
  },
  stageOrder: ["stage-1", "stage-2", "stage-3"],
};
